[package]
name = "hypher-bindings"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Main dependency
hypher = { path = "../../../hypher", features = ["dyn", "build"] }

# Auxiliary dependencies
wasm-minimal-protocol = "0.1.0"

